### ISSUE TITLE
Backward compatibility

### ISSUE THREAD

**Issue by Keith-Hon** [voidful/TextRL#10]
The latest textrl version is not compatible with the exampe below. It works fine with textrl==0.1.6 tho.

https://voidful.dev/jupyter/2022/12/10/textrl-elon-musk.html

**Comment by Keith-Hon** [comment]
also, need to train >100 steps to get obvious result

**Comment by voidful** [comment]
I updated the example to latest version, hops it can solve your issue: https://github.com/voidful/TextRL/blob/main/example/2022-12-10-textrl-elon-musk.ipynb
