### ISSUE TITLE
Is there any examples for T5 or Bart? Why T5 and bart give the same output before/after training?

### ISSUE THREAD

**Issue by YuXiangLin1234** [voidful/TextRL#15]
Hello, 

I used this package to fine-tune a sequence-to-sequence LM, but the prediction after PPO training are always the same with prediction before training.

The things I tried is to change the colab sample code `elon_musk_gpt.ipynb`.
Change model name and from `AutoModelWithLMHead` to  `AutoModelForSeq2SeqLM`  .
<img width="585" alt="image" src="https://user-images.githubusercontent.com/68694649/231401122-b6d7ea4f-5c9e-4d17-9a08-52ddae44f553.png">

When I print out decoded sentences during training, I find that the predicted sentences are changing during each iteration, but the prediction after PPO training are always the same with prediction before training. Is there anything I need to care about? Or Is this package not applicable to sequence-to-sequence LM? 

**Prediction before training:** 
<img width="330" alt="image" src="https://user-images.githubusercontent.com/68694649/231426339-6b1d3e98-b99a-4d47-ad85-a9617e2532bc.png">

**Prediction during iteration:**
<img width="327" alt="image" src="https://user-images.githubusercontent.com/68694649/231426264-38adf058-a827-4387-90fc-231f6b7a9d20.png">

**Prediction after training :**
(
```
pfrl.experiments.train_agent_with_evaluation(
    agent,
    env,
    steps=300,
    eval_n_steps=None,
    eval_n_episodes=1,       
    train_max_episode_len=100,  
    eval_interval=10,
    outdir='elon_musk_dogecoin', 
)

agent.load("./elon_musk_dogecoin/best")
actor.predict(observaton_list[0]) #<------- prediction after training
```
): 
<img width="333" alt="image" src="https://user-images.githubusercontent.com/68694649/231426459-06e20422-3f3d-4edd-aed6-b1063b796131.png">

**Comment by voidful** [comment]
Hi

Thank you for your feedback. I found that it was somehow related to the optimizer, so I updated a new version to enable optimizer settings. 

Here is an example using flan-t5: 
https://colab.research.google.com/drive/1DYHt0mi6cyl8ZTMJEkMNpsSZCCvR4jM1?usp=sharing

**Comment by YuXiangLin1234** [comment]
Thank you very much!
