### ISSUE TITLE
Support for other PFRL Algorithms

### ISSUE THREAD

**Issue by ansharora7** [voidful/TextRL#19]
Is it possible to change the code to use other PFRL Algorithms such as Reinforce? Does this require major changes in multiple files?

**Comment by voidful** [comment]
Thank you for your input. I have previously experimented with different algorithms in PFRL. Based on my understanding, modifying the actor should indeed achieve the desired outcome. I appreciate your suggestion and encourage you to submit a pull request~

**Comment by ansharora7** [comment]
Sure, I am working on something. If I can create a plugin for different RL algorithms, I'll create a pull request.
