### ISSUE TITLE
Does the package support automatic multi-gpu?

### ISSUE THREAD

**Issue by margarita-aicyd** [voidful/TextRL#24]
Hi,

Very excited to find this package useful! 

Does it support multi-gpu? I am dealing with datasets with long input >> 1024, the CUDA-error is reported when initializing the environment. (env = MyEnv(...)).

Everything goes well if I switch to a small input-size.

Thank you!

**Comment by voidful** [comment]
Hi,

I apologize for the inconvenience, but currently, multi-GPU training is not supported. However, you can try using the device_map='auto' option to split the model across available devices. This may help in utilizing multiple GPUs effectively.

Please let me know if you have any further questions or need assistance with anything else.
