### ISSUE TITLE
'Model' object has no attribute 'lm_head'

### ISSUE THREAD

**Issue by Mousumi44** [voidful/TextRL#3]
When I try to initiate the model, I got the error AttributeError: 'XLNetLMHeadModel' object has no attribute 'lm_head'. I tried with Xlnet-base and bert-base model from huggingface. From the readme file it seems the code will work with any model but I failed to do so. Could you please help with that?

Example Code:
```
tokenizer = AutoTokenizer.from_pretrained('xlnet-base-cased')  
model = AutoModelWithLMHead.from_pretrained('xlnet-base-cased')
```

**Comment by voidful** [comment]
this repo is for controllable generation, since Xlnet-base and bert-base are not used for sequence generation, so it may not able to work.
You can try bart or gpt instead~

**Comment by Mousumi44** [comment]
Thanks for your reply. The code worked for bart model. However, I could also make it work for xlnet-base by changing line 16 of actor.py 

```
self.converter.weight = copy.deepcopy(torch.nn.Parameter(self.model.state_dict()['lm_loss.weight']))
```
