### ISSUE TITLE
Could you give some examples to run the code?

### ISSUE THREAD

**Issue by SusannaWull** [voidful/TextRL#5]
I am interested in your project. And I am going to test your project, but I don't know what the input "observaton_list" is and which model you used?

**Comment by voidful** [comment]
observaton_list is a 2d array for all available input，it will be like observaton_list = [['Got any creative ideas for a 10 year old’s birthday?']], and you can either use a causal lm or seq2seq lm in hugging face. here is a small example: https://voidful.dev/jupyter/2022/12/10/textrl-elon-musk.html

**Comment by jaideep11061982** [comment]
@voidful what purpose does observation list serve. I am just trying to understand .
And is this RL or RLHF ?

**Comment by voidful** [comment]
> 

`observation_list` holds the observations that the agent receives from the environment at each step of the RL training. These observations are used by the agent to make decisions and to learn from the environment.

In an RLHF setup, you would need to collect human feedback for the generated text, and then use that feedback as the reward signal to guide the model's learning. You can make this adaptation by changing the reward module in TextRL to incorporate human feedback as the basis for the reward calculation. By doing so, you will create an RLHF setup using TextRL.
